In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("../data/processed/eda_ready_dataset.csv")

print(df.shape)
df.head()

(3629661, 25)

,incident_datetime,initial_call_type,final_call_type,first_assignment_datetime,first_activation_datetime,first_on_scene_datetime,first_to_hosp_datetime,incident_close_datetime,dispatch_response_seconds_qy,incident_response_seconds_qy,...,month,weekday,Weekend,Year,Month,Day,Hour,Weekday,incident_duration,dispatch_delay
0,2024-01-01 00:00:03,INJURY,INJURY,2024-01-01 00:00:56,2024-01-01T00:01:13.000,2024-01-01T00:06:36.000,NaN,2024-01-01 00:56:41,53,393.0,...,1,Monday,False,2024,1,1,0,Monday,3398.0,53.0
1,2024-01-01 00:00:14,CARD,CARD,2024-01-01 00:01:38,2024-01-01T00:01:54.000,2024-01-01T00:07:24.000,2024-01-01T00:26:07.000,2024-01-01 01:19:22,84,430.0,...,1,Monday,False,2024,1,1,0,Monday,4748.0,84.0
2,2024-01-01 00:00:18,STNDBM,STNDBY,2024-01-01 10:17:05,2024-01-01T10:17:05.000,2024-01-01T10:24:18.000,2024-01-01T12:26:21.000,2024-01-01 14:20:21,0,NaN,...,1,Monday,False,2024,1,1,0,Monday,51603.0,37007.0
3,2024-01-01 00:00:45,RESPIR,RESPIR,2024-01-01 00:25:30,2024-01-01T00:25:40.000,2024-01-01T00:32:59.000,2024-01-01T00:50:41.000,2024-01-01 01:37:04,1485,1934.0,...,1,Monday,False,2024,1,1,0,Monday,5779.0,1485.0
4,2024-01-01 00:00:55,BURNMI,BURNMI,2024-01-01 00:01:34,2024-01-01T00:01:57.000,2024-01-01T00:22:50.000,2024-01-01T01:27:23.000,2024-01-01 02:36:27,39,1315.0,...,1,Monday,False,2024,1,1,0,Monday,9332.0,39.0

In [3]:
from sklearn.preprocessing import LabelEncoder
import joblib
import os

os.makedirs("artifacts", exist_ok=True)

categorical_cols = df.select_dtypes(include="object").columns

encoders = {}

for col in categorical_cols:

    le = LabelEncoder()

    df[col] = le.fit_transform(df[col].astype(str))

    encoders[col] = le

    joblib.dump(
        le,
        f"artifacts/{col}_encoder.pkl"
    )

print("✅ All encoders saved successfully!")

✅ All encoders saved successfully!

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3629661 entries, 0 to 3629660
Data columns (total 25 columns):
 #   Column                         Dtype
---  ------                         -----
 0   incident_datetime              str
 1   initial_call_type              str
 2   final_call_type                str
 3   first_assignment_datetime      str
 4   first_activation_datetime      str
 5   first_on_scene_datetime        str
 6   first_to_hosp_datetime         str
 7   incident_close_datetime        str
 8   dispatch_response_seconds_qy   int64
 9   incident_response_seconds_qy   float64
 10  incident_travel_tm_seconds_qy  float64
 11  zipcode                        float64
 12  borough                        str
 13  incident_dispatch_area         str
 14  hour                           int64
 15  month                          int64
 16  weekday                        str
 17  Weekend                        bool
 18  Year                           int64
 19  Month                          int64
 20  Day                            int64
 21  Hour                           int64
 22  Weekday                        str
 23  incident_duration              float64
 24  dispatch_delay                 float64
dtypes: bool(1), float64(5), int64(7), str(12)
memory usage: 668.1 MB

In [56]:
df.describe(include="all")

,incident_datetime,initial_call_type,final_call_type,first_assignment_datetime,first_activation_datetime,first_on_scene_datetime,first_to_hosp_datetime,incident_close_datetime,dispatch_response_seconds_qy,incident_response_seconds_qy,...,month,weekday,Weekend,Year,Month,Day,Hour,Weekday,incident_duration,dispatch_delay
count,3629661,3629661,3629661,3552242,3544974,3408535,2213290,3629181,3.629661e+06,3.407597e+06,...,3.629661e+06,3629661,3629661,3.629661e+06,3.629661e+06,3.629661e+06,3.629661e+06,3629661,3.629181e+06,3.552242e+06
unique,3534454,131,143,3464506,3449917,3321370,2206074,3526288,NaN,NaN,...,NaN,7,2,NaN,NaN,NaN,NaN,7,NaN,NaN
top,2024-09-04 15:25:19,INJURY,SICK,2024-03-06 10:18:10,2024-02-05T18:40:20.000,2024-06-05T21:27:38.000,2024-04-05T20:03:50.000,2024-12-10 02:00:00,NaN,NaN,...,NaN,Monday,False,NaN,NaN,NaN,NaN,Monday,NaN,NaN
freq,5,437223,435316,4,4,5,4,11,NaN,NaN,...,NaN,534086,2636976,NaN,NaN,NaN,NaN,534086,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.048971e+02,9.366330e+02,...,6.049508e+00,NaN,NaN,2.024657e+03,6.049508e+00,1.566941e+01,1.279781e+01,NaN,4.626564e+03,3.216040e+02
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.207944e+03,1.440538e+03,...,3.541763e+00,NaN,NaN,6.621439e-01,3.541763e+00,8.796643e+00,6.442357e+00,NaN,2.911111e+03,1.410593e+03
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,...,1.000000e+00,NaN,NaN,2.024000e+03,1.000000e+00,1.000000e+00,0.000000e+00,NaN,-3.016000e+03,-6.853000e+03
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000e+01,3.770000e+02,...,3.000000e+00,NaN,NaN,2.024000e+03,3.000000e+00,8.000000e+00,8.000000e+00,NaN,3.213000e+03,1.400000e+01
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.900000e+01,5.640000e+02,...,6.000000e+00,NaN,NaN,2.025000e+03,6.000000e+00,1.600000e+01,1.300000e+01,NaN,4.648000e+03,3.000000e+01
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.500000e+01,9.170000e+02,...,9.000000e+00,NaN,NaN,2.025000e+03,9.000000e+00,2.300000e+01,1.800000e+01,NaN,5.784000e+03,8.800000e+01
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.239000e+04,3.239600e+04,...,1.200000e+01,NaN,NaN,2.026000e+03,1.200000e+01,3.100000e+01,2.300000e+01,NaN,1.006130e+05,7.449400e+04

In [57]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing

first_to_hosp_datetime           1416371
incident_response_seconds_qy      222064
incident_travel_tm_seconds_qy     221185
first_on_scene_datetime           221126
first_activation_datetime          84687
first_assignment_datetime          77419
dispatch_delay                     77419
zipcode                            42641
incident_close_datetime              480
incident_duration                    480
dtype: int64

In [58]:
missing_percent = (df.isnull().sum()/len(df))*100

missing_percent = missing_percent[missing_percent>0].sort_values(ascending=False)

missing_percent

first_to_hosp_datetime           39.022129
incident_response_seconds_qy      6.118037
incident_travel_tm_seconds_qy     6.093820
first_on_scene_datetime           6.092194
first_activation_datetime         2.333193
first_assignment_datetime         2.132954
dispatch_delay                    2.132954
zipcode                           1.174793
incident_close_datetime           0.013224
incident_duration                 0.013224
dtype: float64

In [59]:
threshold = 70

cols_to_drop = missing_percent[missing_percent > threshold].index

print(cols_to_drop)

df.drop(columns=cols_to_drop, inplace=True)

Index([], dtype='str')

In [60]:
target_cols = [
    "dispatch_response_seconds_qy",
    "incident_response_seconds_qy",
    "incident_travel_tm_seconds_qy"
]

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:

    if col not in target_cols:

        df[col] = df[col].fillna(df[col].median())

In [61]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:

    df[col] = df[col].fillna(df[col].mode()[0])

In [62]:
print("Duplicate Rows :", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print(df.shape)

Duplicate Rows : 0
(3629661, 25)

In [63]:
datetime_cols = [
    "incident_datetime",
    "first_assignment_datetime",
    "first_activation_datetime",
    "first_on_scene_datetime",
    "first_to_hosp_datetime",
    "incident_close_datetime"
]

for col in datetime_cols:

    if col in df.columns:

        df[col] = pd.to_datetime(df[col], errors="coerce")

In [64]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:

    if col not in target_cols:

        df.loc[df[col] < 0, col] = df[col].median()

In [65]:
categorical_cols = df.select_dtypes(include="object").columns

encoder = LabelEncoder()

for col in categorical_cols:

    df[col] = encoder.fit_transform(df[col].astype(str))

In [66]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:

    if col not in target_cols:

        Q1 = df[col].quantile(0.25)

        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR

        upper = Q3 + 1.5 * IQR

        df[col] = np.where(df[col] < lower, lower, df[col])

        df[col] = np.where(df[col] > upper, upper, df[col])

In [67]:
missing = df.isnull().sum()

missing[missing > 0]

incident_response_seconds_qy     222064
incident_travel_tm_seconds_qy    221185
dtype: int64

In [68]:
print("="*60)

print("Dataset Shape :", df.shape)

print("Missing Values :", df.isnull().sum().sum())

print("Duplicate Rows :", df.duplicated().sum())

print("="*60)

============================================================
Dataset Shape : (3629661, 25)
Missing Values : 443249
Duplicate Rows : 0
============================================================

In [69]:
df.to_csv("../data/processed/EMS_Cleaned.csv", index=False)

print("EMS_Cleaned.csv Saved Successfully!")

EMS_Cleaned.csv Saved Successfully!

In [70]:
print(df.columns.tolist())

['incident_datetime', 'initial_call_type', 'final_call_type', 'first_assignment_datetime', 'first_activation_datetime', 'first_on_scene_datetime', 'first_to_hosp_datetime', 'incident_close_datetime', 'dispatch_response_seconds_qy', 'incident_response_seconds_qy', 'incident_travel_tm_seconds_qy', 'zipcode', 'borough', 'incident_dispatch_area', 'hour', 'month', 'weekday', 'Weekend', 'Year', 'Month', 'Day', 'Hour', 'Weekday', 'incident_duration', 'dispatch_delay']