In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/processed/EMS_Cleaned.csv")

print(df.columns.tolist())

['incident_datetime', 'initial_call_type', 'final_call_type', 'first_assignment_datetime', 'first_activation_datetime', 'first_on_scene_datetime', 'first_to_hosp_datetime', 'incident_close_datetime', 'dispatch_response_seconds_qy', 'incident_response_seconds_qy', 'incident_travel_tm_seconds_qy', 'zipcode', 'borough', 'incident_dispatch_area', 'hour', 'month', 'weekday', 'Weekend', 'Year', 'Month', 'Day', 'Hour', 'Weekday', 'incident_duration', 'dispatch_delay']

In [3]:
df = pd.read_csv("../data/processed/EMS_Cleaned.csv")

datetime_cols = [
    "incident_datetime",
    "first_assignment_datetime",
    "first_activation_datetime",
    "first_on_scene_datetime",
    "first_to_hosp_datetime",
    "incident_close_datetime"
]

print(df.shape)
df.head()

(3629661, 25)

,incident_datetime,initial_call_type,final_call_type,first_assignment_datetime,first_activation_datetime,first_on_scene_datetime,first_to_hosp_datetime,incident_close_datetime,dispatch_response_seconds_qy,incident_response_seconds_qy,incident_travel_tm_seconds_qy,zipcode,borough,incident_dispatch_area,hour,month,weekday,Weekend,Year,Month,Day,Hour,Weekday,incident_duration,dispatch_delay
0,2024-01-01 00:00:03,53.0,51.0,2024-01-01 00:00:56,2024-01-01 00:01:13,2024-01-01 00:06:36,2024-04-05 20:03:50,2024-01-01 00:56:41,53,393.0,340.0,11365.0,3.0,26.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,3398.0,53.0
1,2024-01-01 00:00:14,21.0,17.0,2024-01-01 00:01:38,2024-01-01 00:01:54,2024-01-01 00:07:24,2024-01-01 00:26:07,2024-01-01 01:19:22,84,430.0,346.0,10457.0,0.0,1.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,4748.0,84.0
2,2024-01-01 00:00:18,99.0,111.0,2024-01-01 10:17:05,2024-01-01 10:17:05,2024-01-01 10:24:18,2024-01-01 12:26:21,2024-01-01 14:20:21,0,NaN,433.0,11224.0,1.0,6.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,9640.5,191.5
3,2024-01-01 00:00:45,84.0,95.0,2024-01-01 00:25:30,2024-01-01 00:25:40,2024-01-01 00:32:59,2024-01-01 00:50:41,2024-01-01 01:37:04,1485,1934.0,449.0,10033.0,2.0,21.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,5779.0,191.5
4,2024-01-01 00:00:55,20.0,16.0,2024-01-01 00:01:34,2024-01-01 00:01:57,2024-01-01 00:22:50,2024-01-01 01:27:23,2024-01-01 02:36:27,39,1315.0,1276.0,11208.0,1.0,9.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,9332.0,39.0

In [4]:
df["peak_hour"] = (
    ((df["hour"] >= 7) & (df["hour"] <= 10)) |
    ((df["hour"] >= 16) & (df["hour"] <= 19))
).astype(int)

In [5]:
df["night_shift"] = (
    (df["hour"] >= 22) |
    (df["hour"] <= 5)
).astype(int)

In [6]:
print(df[["first_activation_datetime", "first_on_scene_datetime"]].dtypes)

first_activation_datetime    str
first_on_scene_datetime      str
dtype: object

In [7]:
print(df["first_activation_datetime"].head(10))
print(df["first_on_scene_datetime"].head(10))

0    2024-01-01 00:01:13
1    2024-01-01 00:01:54
2    2024-01-01 10:17:05
3    2024-01-01 00:25:40
4    2024-01-01 00:01:57
5    2024-01-01 00:01:54
6    2024-01-01 00:02:14
7    2024-02-05 18:40:20
8    2024-01-01 00:02:21
9    2024-01-01 00:03:43
Name: first_activation_datetime, dtype: str
0    2024-01-01 00:06:36
1    2024-01-01 00:07:24
2    2024-01-01 10:24:18
3    2024-01-01 00:32:59
4    2024-01-01 00:22:50
5    2024-01-01 00:18:42
6    2024-01-01 00:08:53
7    2024-06-05 21:27:38
8    2024-01-01 00:13:01
9    2024-01-01 00:06:52
Name: first_on_scene_datetime, dtype: str

In [8]:
datetime_cols = [
    "incident_datetime",
    "first_assignment_datetime",
    "first_activation_datetime",
    "first_on_scene_datetime",
    "first_to_hosp_datetime",
    "incident_close_datetime"
]

for col in datetime_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

In [9]:
print(df["first_activation_datetime"].head())
print(df["first_on_scene_datetime"].head())

0   2024-01-01 00:01:13
1   2024-01-01 00:01:54
2   2024-01-01 10:17:05
3   2024-01-01 00:25:40
4   2024-01-01 00:01:57
Name: first_activation_datetime, dtype: datetime64[us]
0   2024-01-01 00:06:36
1   2024-01-01 00:07:24
2   2024-01-01 10:24:18
3   2024-01-01 00:32:59
4   2024-01-01 00:22:50
Name: first_on_scene_datetime, dtype: datetime64[us]

In [10]:
df["travel_duration"] = (
    df["first_on_scene_datetime"] -
    df["first_activation_datetime"]
).dt.total_seconds()

print(df["travel_duration"].head())

0     323.0
1     330.0
2     433.0
3     439.0
4    1253.0
Name: travel_duration, dtype: float64

In [11]:
df["hospital_time"] = (
    df["first_to_hosp_datetime"] -
    df["first_on_scene_datetime"]
).dt.total_seconds()

In [12]:
df["closure_time"] = (
    df["incident_close_datetime"] -
    df["first_to_hosp_datetime"]
).dt.total_seconds()

In [13]:
df["zipcode_frequency"] = df["zipcode"].map(
    df["zipcode"].value_counts()
)

In [14]:
df["borough_frequency"] = df["borough"].map(
    df["borough"].value_counts()
)

In [15]:
df["dispatch_area_frequency"] = df["incident_dispatch_area"].map(
    df["incident_dispatch_area"].value_counts()
)

In [16]:
df["initial_call_frequency"] = df["initial_call_type"].map(
    df["initial_call_type"].value_counts()
)

In [17]:
df["final_call_frequency"] = df["final_call_type"].map(
    df["final_call_type"].value_counts()
)

In [18]:
df["rush_hour"] = df["hour"].isin([7, 8, 9, 16, 17, 18, 19]).astype(int)

df["office_hours"] = df["hour"].between(9, 17).astype(int)

df["call_borough"] = (
    df["initial_call_type"].astype(str) + "_" +
    df["borough"].astype(str)
).astype("category").cat.codes

df["zip_hour"] = (
    df["zipcode"].astype(str) + "_" +
    df["hour"].astype(str)
).astype("category").cat.codes

print("New Features Added Successfully!")

New Features Added Successfully!

In [19]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:

    df[col] = df[col].fillna(df[col].median())

In [20]:
df.drop(columns=datetime_cols, inplace=True, errors="ignore")

In [21]:
print(df.shape)

print(df.isnull().sum().sum())

df.head()

(3629661, 33)
0

,initial_call_type,final_call_type,dispatch_response_seconds_qy,incident_response_seconds_qy,incident_travel_tm_seconds_qy,zipcode,borough,incident_dispatch_area,hour,month,weekday,Weekend,Year,Month,Day,Hour,Weekday,incident_duration,dispatch_delay,peak_hour,night_shift,travel_duration,hospital_time,closure_time,zipcode_frequency,borough_frequency,dispatch_area_frequency,initial_call_frequency,final_call_frequency,rush_hour,office_hours,call_borough,zip_hour
0,53.0,51.0,53,393.0,340.0,11365.0,3.0,26.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,3398.0,53.0,0,1,323.0,8279834.0,-8276829.0,9311,743558,43405,437223,416373,0,0,337,4244
1,21.0,17.0,84,430.0,346.0,10457.0,0.0,1.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,4748.0,84.0,0,1,330.0,1123.0,3195.0,59102,854212,253459,188550,197297,0,0,180,2298
2,99.0,111.0,0,564.0,433.0,11224.0,1.0,6.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,9640.5,191.5,0,1,433.0,7323.0,6840.0,34013,1002290,150556,985,8795,0,0,536,3547
3,84.0,95.0,1485,1934.0,449.0,10033.0,2.0,21.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,5779.0,191.5,0,1,439.0,1062.0,2783.0,25033,873477,98891,33155,27167,0,0,470,744
4,20.0,16.0,39,1315.0,1276.0,11208.0,1.0,9.0,0.0,1.0,1.0,False,2024.0,1.0,1.0,0.0,1.0,9332.0,39.0,0,1,1253.0,3873.0,4144.0,51519,1002290,252294,3778,3513,0,0,176,3163

In [22]:
print(df.columns.tolist())

['initial_call_type', 'final_call_type', 'dispatch_response_seconds_qy', 'incident_response_seconds_qy', 'incident_travel_tm_seconds_qy', 'zipcode', 'borough', 'incident_dispatch_area', 'hour', 'month', 'weekday', 'Weekend', 'Year', 'Month', 'Day', 'Hour', 'Weekday', 'incident_duration', 'dispatch_delay', 'peak_hour', 'night_shift', 'travel_duration', 'hospital_time', 'closure_time', 'zipcode_frequency', 'borough_frequency', 'dispatch_area_frequency', 'initial_call_frequency', 'final_call_frequency', 'rush_hour', 'office_hours', 'call_borough', 'zip_hour']

In [23]:
df.drop(columns=["Hour", "Month", "Day", "Weekday"], inplace=True)

In [ ]:
import joblib
import os

os.makedirs("artifacts", exist_ok=True)

zipcode_frequency = df["zipcode"].value_counts().to_dict()
borough_frequency = df["borough"].value_counts().to_dict()
initial_call_frequency = df["initial_call_type"].value_counts().to_dict()
final_call_frequency = df["final_call_type"].value_counts().to_dict()
dispatch_area_frequency = df["incident_dispatch_area"].value_counts().to_dict()

joblib.dump(zipcode_frequency, "artifacts/zipcode_frequency.pkl")
joblib.dump(borough_frequency, "artifacts/borough_frequency.pkl")
joblib.dump(initial_call_frequency, "artifacts/initial_call_frequency.pkl")
joblib.dump(final_call_frequency, "artifacts/final_call_frequency.pkl")
joblib.dump(dispatch_area_frequency, "artifacts/dispatch_area_frequency.pkl")

['artifacts/dispatch_area_frequency.pkl']

In [25]:
call_borough_mapping = {
    k: i for i, k in enumerate(
        (df["initial_call_type"].astype(str) + "_" +
         df["borough"].astype(str)).astype("category").cat.categories
    )
}

joblib.dump(
    call_borough_mapping,
    "artifacts/call_borough_mapping.pkl"
)

['artifacts/call_borough_mapping.pkl']

In [26]:
zip_hour_mapping = {
    k: i for i, k in enumerate(
        (df["zipcode"].astype(str) + "_" +
         df["hour"].astype(str)).astype("category").cat.categories
    )
}

joblib.dump(
    zip_hour_mapping,
    "artifacts/zip_hour_mapping.pkl"
)

['artifacts/zip_hour_mapping.pkl']

In [27]:
print("BOROUGH")
print(sorted(df["borough"].unique().tolist()))

print("\nINITIAL CALL TYPE")
print(sorted(df["initial_call_type"].unique().tolist()))

print("\nFINAL CALL TYPE")
print(sorted(df["final_call_type"].unique().tolist()))

print("\nDISPATCH AREA")
print(sorted(df["incident_dispatch_area"].unique().tolist()))

BOROUGH
[0.0, 1.0, 2.0, 3.0, 3.5]

INITIAL CALL TYPE
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 116.0, 117.0, 118.0, 119.0, 120.0, 121.0, 122.0, 123.0, 124.0, 125.0, 126.0, 127.0, 128.0, 129.0, 130.0]

FINAL CALL TYPE
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 116.0, 117.0, 118.0, 119.0, 120.0, 121.0, 122.0, 123.0, 124.0, 125.0, 126.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 137.0, 138.0, 139.0, 140.0, 141.0, 142.0]

DISPATCH AREA
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0]

In [ ]:
import joblib
import os

os.makedirs("artifacts", exist_ok=True)

joblib.dump(le_borough, "artifacts/le_borough.pkl")
joblib.dump(le_initial, "artifacts/le_initial_call.pkl")
joblib.dump(le_final, "artifacts/le_final_call.pkl")
joblib.dump(le_dispatch, "artifacts/le_dispatch_area.pkl")

In [28]:
print(df["zipcode"].nunique())

237

In [25]:
df.to_csv("../data/processed/EMS_Feature_Engineered.csv", index=False)

print("Feature Engineering Completed Successfully.")

Feature Engineering Completed Successfully.